### ISSUE TITLE
关于超内存问题

### ISSUE THREAD

**Issue by Jamie-Cheung** [Kunhao-Liu/StyleRF#2]
请问，我在进行 Feature grid training stage过程中，出现超内存问题导致训练代码被中断，尽管我的电脑是128G的内存容量依然不行，能告知一下您用的是多少的内存吗，或者是否有其他的解决办法。
Traceback (most recent call last):
  File "/home/zzj/disk1/zzj/StyleRF-main/train_feature.py", line 290, in <module>
    reconstruction(args)
  File "/home/zzj/disk1/zzj/StyleRF-main/train_feature.py", line 148, in reconstruction
    train_dataset.prepare_feature_data(tensorf.encoder)
  File "/home/zzj/anaconda3/envs/StyleRF/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/zzj/disk1/zzj/StyleRF-main/dataLoader/blender.py", line 119, in prepare_feature_data
    features.append(features_chunk.detach().cpu().requires_grad_(False))
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 5242880000 bytes. Error code 12 (Cannot allocate memory)

**Comment by Kunhao-Liu** [comment]
我用的是256G内存的服务器，但是训练时内存的占用只有30G，是不是你有其他的进程占用了过多的内存呢？

**Comment by Jamie-Cheung** [comment]
> 我用的是256G内存的服务器，但是训练时内存的占用只有30G，是不是你有其他的进程占用了过多的内存呢？

训练的时候确实要不了多少内存，但是加载的时候内存使用在一直增长，我降低了输入图片的尺寸才能正常运行

**Comment by jly0810** [comment]
> > 我用的是256G内存的服务器，但是训练时内存的占用只有30G，是不是你还有其他的进程占用了过多的内存呢？
> 
> 训练的时候确实要不了多少内存，但是加载的时候内存使用一直增长，我降低了输入图片的大小才能正常运行

您好 我想问一下您具体是怎么操作的 我也遇到了内存不够的情况
